"""Module 20 — Attack Path Builder.

Builds a directed graph of findings -> exploits -> impacts and generates
Mermaid-compatible diagrams representing the business risk.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


class AttackPathBuilder:
    """Build directed attack paths and generate Mermaid diagrams."""

    def __init__(self, http: Any = None) -> None:
        pass  # Pure analysis module

    async def run(
        self,
        base_url: str,
        observations: list[dict[str, Any]],
        findings: list[dict[str, Any]] | None = None,
        **kwargs: Any,
    ) -> list[dict[str, Any]]:
        if not findings:
            return []

        # Only run if we have chain findings (generated by Module 3)
        chain_findings = [f for f in findings if f.get("category") == "vuln-chain"]
        if not chain_findings:
            return []

        target = base_url.rstrip("/")
        diagram = self._generate_mermaid(chain_findings)

        return [{
            "id": "ATTACK-PATH-GRAPH",
            "title": "Visual Attack Path Graph (Mermaid)",
            "severity": "info",
            "confidence": "high",
            "category": "reporting",
            "target": target,
            "evidence": (
                "The following Mermaid.js graph illustrates the identified "
                "multi-step attack paths.\n\n"
                "```mermaid\n"
                f"{diagram}\n"
                "```"
            ),
            "recommendation": (
                "Use this graph to understand the relationship between "
                "low-level vulnerabilities and high-level business impact. "
                "Prioritize breaking the earliest nodes in the chains."
            ),
        }]

    def _generate_mermaid(self, chain_findings: list[dict[str, Any]]) -> str:
        lines = ["graph TD"]
        lines.append("    classDef crit fill:#ff3355,stroke:#fff,stroke-width:2px,color:#fff;")
        lines.append("    classDef high fill:#ff6b35,stroke:#fff,stroke-width:2px,color:#fff;")
        lines.append("    classDef entry fill:#448aff,stroke:#fff,stroke-width:2px,color:#fff;")

        lines.append("    Attacker((Attacker)):::entry")

        for idx, chain in enumerate(chain_findings):
            chain_id = f"Chain{idx}"
            title = chain.get("title", f"Attack Chain {idx}").replace("Attack Chain: ", "")
            sev = chain.get("severity", "high")
            sev_class = ":::crit" if sev == "critical" else ":::high"

            lines.append(f"    {chain_id}[\"{title}\"]{sev_class}")
            lines.append(f"    Attacker --> {chain_id}")

            # Extract steps from evidence text
            evidence = str(chain.get("evidence", ""))
            steps = []
            for line in evidence.split("\n"):
                line = line.strip()
                if line and line[0].isdigit() and ". " in line:
                    steps.append(line.split(". ", 1)[1])

            prev_node = chain_id
            for step_idx, step_text in enumerate(steps):
                # Clean text for Mermaid (remove quotes)
                safe_text = step_text.replace('"', "'").replace("(", "[").replace(")", "]")
                # Wrap text if it's too long
                if len(safe_text) > 40:
                    safe_text = safe_text[:37] + "..."

                step_id = f"S{idx}_{step_idx}"
                lines.append(f"    {step_id}[\"{safe_text}\"]")
                lines.append(f"    {prev_node} --> {step_id}")
                prev_node = step_id

            # Add final impact node
            impact_id = f"Impact{idx}"
            lines.append(f"    {impact_id}((\"Business Impact\")):::crit")
            lines.append(f"    {prev_node} -->|Results In| {impact_id}")

        return "\n".join(lines)
